src/app.py
from flask import Flask, render_template

import os
import sys

if len(sys.argv) > 1 and sys.argv[1] == 'env':
    """ 
    Sets the environmental variables when run locally.
    'make_env' package is not distributed.
    """
    import make_env
    make_env.set_env()


__author__ = 'scul@gitlab.com'


app = Flask(__name__)
app.config.from_object('src.config')

app.secret_key = os.environ['SECRET_KEY']

from src.common.database import Database


@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def index():
    return render_template('home.jinja2')


from src.models.users.views import user_blueprint
from src.models.stocks.views import stock_blueprint

app.register_blueprint(user_blueprint, url_prefix='/users')
app.register_blueprint(stock_blueprint, url_prefix='/stocks')

src/models/stocks/views.py
from flask import Blueprint, request, session, redirect, url_for, flash
from src.models.users.user import User
from src.models.stocks.stock import Stock
import src.common.decorators as user_decorators
import src.models.stocks.errors as StockErrors


__author__ = 'scul@gitlab.com'
__copyright__ = "Copyright 2018, scul@gitlab.com"
__license__ = "GPLv3 or later"

stock_blueprint = Blueprint('stocks', __name__)


@stock_blueprint.route('/new', methods=['POST'])
@user_decorators.requires_login
def new_stock():
    if request.method == 'POST':
        symbols = [symbol.strip() for symbol in request.form['symbol'].upper().split(',')]
        print(symbols)
        user = User.get_by_name(session['name'])
        for symbol in symbols:
            try:
                Stock.new_stock(symbol)
                if len(symbol.strip()) >= 1:
                    user.add_stock(symbol)
            except (StockErrors.StockError, StockErrors.SymbolError) as e:
                flash(e.message, 'danger')
        return redirect(url_for('users.stocks'))


@stock_blueprint.route('/delete', methods=['POST'])
@user_decorators.requires_login
def remove_stock():
    stock_symbol = request.form['stock_symbol']
    User.get_by_name(session['name']).remove_stock(stock_symbol)
    flash(f'Removed {stock_symbol} from your tracking.', 'info')
    return redirect(url_for('users.stocks'))

src/models/users/views.py
from flask import Blueprint, request, url_for, session, render_template, flash
from werkzeug.utils import redirect
from src.models.users.user import User
from src.common.utils import Utils
import src.common.decorators as common_decorators
import src.models.users.errors as UserErrors

__author__ = 'scul@gitlab.com'
__copyright__ = "Copyright 2018, scul@gitlab.com"
__license__ = "GPLv3 or later"


user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
@common_decorators.requires_logout
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        try:
            if User.is_login_valid(username, password):
                session['name'] = username
                return redirect(url_for('users.stocks'))
        except UserErrors.UserError:
            flash('Username or password incorrect!', 'danger')

    return render_template('users/login.jinja2')


@user_blueprint.route('/logout')
@common_decorators.requires_login
def logout():
    session['name'] = None
    return redirect(url_for('index'))


@user_blueprint.route('/register', methods=['GET', 'POST'])
@common_decorators.requires_logout
def register():
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        if request.form.getlist('sub'):
            sub = True
        else:
            sub = False
        password = request.form['password']
        password2 = request.form['password2']
        timezone = None

        try:
            if User.register(username, email, password, password2, sub, timezone):
                session['name'] = username
                return redirect(url_for('users.stocks'))
        except UserErrors.UserError as e:
            flash(e.message, 'danger')
    return render_template('users/register.jinja2')


@user_blueprint.route('/profile', methods=['GET', 'POST'])
@common_decorators.requires_login
def profile():
    user = User.get_by_name(session['name'])
    if request.method == 'POST':
        action = request.form['action']
        if action == 'name':
            try:
                user.name = request.form['name']
                session['name'] = user.name
            except (AttributeError, UserErrors.UserNameUsedError) as e:
                flash(e.message, 'danger')

        elif action == 'email':
            try:
                user.update_email(request.form['email'])
            except UserErrors.EmailInvalidError as e:
                flash(e.message, 'danger')

        elif action == 'sub':
            user.toggle_subscription()

        elif action == 'password':
            curr_password = request.form['curr_password']
            passwd1 = request.form['new_password1']
            passwd2 = request.form['new_password2']
            if Utils.verify_password(curr_password, user.password_hash) and passwd1 == passwd2:
                user.password = passwd1
                flash('Password changed', 'success')
            else:
                flash('Invalid password or New passwords do not match', 'danger')

        elif action == 'delete':
            if user.name == request.form['name']:
                user.delete_account()
                flash('Account Deleted', 'success')
                return redirect(url_for('users.logout'))
            else:
                flash('Account name mis-match', 'info')

        return redirect(url_for('users.profile'))
    return render_template('users/profile.jinja2', user=user)


@user_blueprint.route('/stocks')
@common_decorators.requires_login
def stocks():
    user = User.get_by_name(session['name'])
    stocks = sorted(user.get_stocks(), key=lambda stock:stock.symbol)
    return render_template('users/stocks.jinja2', user=user.name, stocks=stocks)

src/templates/_inline_message.jinja2
{% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div class="flash">
                {% if category == 'danger' %}
                    <span class="glyphicon glyphicon-exclamation-sign"></span>
                {% elif category == 'success' %}
                    <span class="glyphicon glyphicon-ok-sign"></span>
                {% elif category == 'info' %}
                    <span class="glyphicon glyphicon-info-sign"></span>
                {% endif %}
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endwith %}

src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Hello{% endblock %}</title>

        {% include 'html_dependencies.jinja2' %}
        {% block css_includes %}{% endblock %}
    {% endblock %}

</head>
<body>

<div class="navbar navbar-fixed-top navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" title="Home">Home</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if session['name'] %}
                    <li><a href="{{ url_for('users.stocks') }}" title="Stocks"><span class="glyphicon glyphicon-stats"></span> Stocks</a></li>
                    <li><a href="{{ url_for('users.profile') }}" title="Profile"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
                    <li><a href="{{ url_for('users.logout') }}" title="Log Out"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
                {% else %}
                    <li><a href="{{ url_for('users.register') }}" title="Sign up"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
                    <li><a href="{{ url_for('users.login') }}" title="Log in"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
<div class="content container">
    {% block content %}

    {% endblock %}
</div>


<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
      <div class="row">
          <a href="https://gitlab.com/scul/market-watch" class="col-xs-1 col-xs-offset-8 col-sm-offset-10" rel="noopener noreferrer" target="_blank">
            <img src="{{ url_for('static', filename='img/gitlab_no_bg.png') }}" class="navbar-text navbar-right" alt="Responsive image" height="25px">
          </a>
      </div>
  </div>
</nav>

</body>
</html>

src/templates/home.jinja2
{% extends "base.jinja2" %}
{%  block title %}Home{% endblock %}
{% block content %}
    {% block flash_messages %}
        {% include '_inline_message.jinja2' %}
    {% endblock %}
    <div class="jumbotron">
        <h1>ARFCOM Market Watch</h1>
        <p>This was made after a suggestion on ARF for a tool to keep track of stock prices</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register') }}" role="button">Get started</a></p>
    </div>
    <small>Copyright (C) GPLv3 2018  scul@gitlab.com</small>
{% endblock %}

src/templates/html_dependencies.jinja2
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<!-- Latest compiled and minified Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<link rel="icon" href="{{ url_for('static', filename='img/Icon.png') }}" type="image/png">

<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<!-- Latest compiled and minified Bootstrap JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!--script src="{{ url_for('static', filename='js/scripts.js') }}"></script-->

src/templates/stocks/_new_stock_modal.jinja2
<div class="modal fade" id="newStockModal" tabindex="-1" role="dialog" aria-labelledby="newStockModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="newStockModalLabel">Add a stock to your tracking</h4>
            </div>
            <form action="{{ url_for('stocks.new_stock') }}" method="post" class="form-horizontal">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">Stock Symbol</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="symbol" name="symbol" placeholder="Symbol"
                                   aria-describedby="stockSymbolHelpBlock" autofocus>
                            <p class="help-block">Enter multiple stocks separated with commas</p>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-sm-offset-2">
                        <button type="submit" class="btn btn-default">Track Stock</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

src/templates/users/_delete_user_modal.jinja2
<div class="modal fade" id="deleteUserModal" tabindex="-1" role="dialog" aria-labelledby="deleteUserModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="deleteUserModalLabel">Delete User Account</h4>
            </div>
            <form action="{{ url_for('users.profile') }}" method="post" class="form-horizontal">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name" class="col-sm-3 control-label">Enter account name to confirm: </label>
                        <div class="col-sm-7">
                            <input type="text" name="name" class="form-control"/>
                        </div>
                        <input type="hidden" name="action" id="action" value="delete"/>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-xs-4 col-xs-offset-8">
                            <button type="submit" class="btn btn-danger">Delete</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

src/templates/users/_email_modal.jinja2
<div class="modal fade" id="emailModal" tabindex="-1" role="dialog" aria-labelledby="emailModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="stockModalLabel">Change email</h4>
            </div>
            <form action="{{ url_for('users.profile') }}" method="post" class="form-horizontal">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">New Email: </label>
                        <div class="col-sm-7">
                            <input type="email" class="form-control" name="email" placeholder="{{ user.email }}"/>
                        </div>
                        <input type="hidden" name="action" id="action" value="email"/>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-xs-4 col-xs-offset-8">
                            <button type="submit" class="btn btn-primary">Update</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

src/templates/users/_name_modal.jinja2
<div class="modal fade" id="nameModal" tabindex="-1" role="dialog" aria-labelledby="nameModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="nameModalLabel">Change user name</h4>
            </div>
            <form action="{{ url_for('users.profile') }}" method="post" class="form-horizontal">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">New name: </label>
                        <div class="col-sm-7">
                            <input type="name" class="form-control" name="name" placeholder="{{ user.name }}"/>
                        </div>
                        <input type="hidden" name="action" id="action" value="name"/>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-xs-4 col-xs-offset-8">
                            <button type="submit" class="btn btn-primary">Update</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

src/templates/users/_password_modal.jinja2
<div class="modal fade" id="passwordModal" tabindex="-1" role="dialog" aria-labelledby="passwordModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="stockModalLabel">Change password</h4>
            </div>
            <form action="{{ url_for('users.profile') }}" method="post" class="form-horizontal">
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group">
                            <label for="email" class="col-sm-4 control-label">Current Password: </label>
                            <div class="col-sm-7">
                                <input type="password" name="curr_password" class="form-control"/>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="form-group">
                            <label for="email" class="col-sm-4 control-label">New Password: </label>
                            <div class="col-sm-7">
                                <input type="password" name="new_password1" class="form-control"/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label for="email" class="col-sm-4 control-label">Confirm Password: </label>
                            <div class="col-sm-7">
                                <input type="password" name="new_password2" class="form-control"/>
                            </div>
                            <input type="hidden" name="action" id="action" value="password"/>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-xs-4 col-xs-offset-8">
                          <button type="submit" class="btn btn-primary">Update</button>
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

src/templates/users/_stock_modal.jinja2
<div class="modal fade" id="{{ stock.symbol }}Modal" tabindex="-1" role="dialog" aria-labelledby="stockModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="stockModalLabel">Stock data for {{ stock.symbol }}</h4>
            </div>
            <div class="modal-body">
                <div class="stock-history">
                   <table class="table table-bordered">
                       <tr>
                           <th>Date</th>
                           <th>Price</th>
                       </tr>
                       {% for date, price in stock.price_history.items() %}
                           <tr>
                               <td> {{ date }}</td>
                               <td> {{ price }}</td>
                           </tr>
                       {% endfor %}
                   </table>
                </div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-xs-1">
                        <form action="{{ url_for('stocks.remove_stock') }}" method="post" onsubmit="return confirmDelete()">
                            <input type="hidden" name="stock_symbol" value="{{ stock.symbol }}" />
                            <button type="submit" class="btn btn-danger">Remove</button>
                        </form>
                    </div>
                    <div class="col-xs-3 col-xs-offset-8">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/templates/users/login.jinja2
{% extends "base.jinja2" %}
{% block title %}Login {% endblock %}
{% block content %}
    <div class="form">
        {% block flash_messages %}
            {% include '_inline_message.jinja2' %}
        {% endblock %}
        <form action="{{ url_for('users.login') }}" method="post" class="form-horizontal col-sm-8 col-sm-offset-1">
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">User Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="username" name="username" placeholder="User Name"
                       aria-describedby="usernameHelpBlock" autofocus>
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                </div>
            </div>
            <div class="col-sm-10 col-sm-offset-2">
                <button type="submit" class="btn btn-default">Log in</button>
            </div>
        </form>
    </div>
{% endblock %}

src/templates/users/profile.jinja2
{% extends "base.jinja2" %}
{% block title %} Profile {% endblock %}
{% block content %}
    <div class="container">
        {% block flash_messages %}
            {% include '_inline_message.jinja2' %}
        {% endblock %}
        <div class="row">
            <h2>Profile for {{ user.name }}</h2>
        </div>
        <hr>
        <div class="row">
             <label class="col-sm-2 control-label" for="email">Name</label>
             <div class="col-sm-4">
                 <p class="form-contol-static">{{ user.name }}</p>
             </div>
             <a href="#" type="submit" data-toggle="modal" data-target="#nameModal" class="btn btn-default">Change name</a>
             {% include 'users/_name_modal.jinja2' %}
        </div>
        <hr>
        <div class="row">
             <label class="col-sm-2 control-label" for="email">e-Mail</label>
             <div class="col-sm-4">
                 <p class="form-contol-static">{{ user.email }}</p>
             </div>
             <a href="#" type="submit" data-toggle="modal" data-target="#emailModal" class="btn btn-default">Change e-Mail</a>
             {% include 'users/_email_modal.jinja2' %}
        </div>
        <hr>
        <div class="row">
            <label class="col-sm-2 control-label" for="sub">e-Mail Updates: </label>
            <div class="col-sm-4">
                {% if user.sub %}
                    <p class="form-contol-static">Active</p>
                {% else %}
                    <p class="form-contol-static">Inactive</p>
                {% endif %}
            </div>
            <form class="form-horizontal" action="{{ url_for('users.profile') }}" method="post">
                <input type="hidden" name="action" id="action" value="sub"/>
                <button type="submit" class="btn btn-default">Toggle</button>
            </form>
        </div>
        <hr>
        <div class="row">
            <label class="col-sm-2 control-label" for="sub">Password: </label>
            <div class="col-sm-4">
                **********
            </div>
            <a href="#" type="submit" data-toggle="modal" data-target="#passwordModal" class="btn btn-default">Change password</a>
            {% include 'users/_password_modal.jinja2' %}
         </div>
        <hr>
        <div class="row">
            <label class="col-sm-2 control-label" for="sub">Delete your Account:</label>
            <div class="col-sm-4">
                This is permanent!
            </div>
            <a href="#" type="submit" data-toggle="modal" data-target="#deleteUserModal" class="btn btn-danger">Delete Account</a>
            {% include 'users/_delete_user_modal.jinja2' %}
         </div>
    </div>
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
{% endblock %}

src/templates/users/register.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form">
        {% block flash_messages %}
            {% include '_inline_message.jinja2' %}
        {% endblock %}
        <form action="{{ url_for('users.register') }}" method="post" class="form-horizontal col-sm-8 col-sm-offset-1">
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">User Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="username" name="username" placeholder="User Name" autofocus>
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="email" name="email" placeholder="example@example.com">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div class="checkbox">
                        <label>
                              <input type="checkbox" id="sub" name="sub" checked> Email me notifications when stocks are below threshold
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                </div>
                <div class="col-sm-10 col-sm-offset-2">
                    <input type="password" class="form-control" name="password2" id="password2" placeholder="Verify password">
                </div>
            </div>
            <div class="col-sm-10 col-sm-offset-2">
                <button type="submit" class="btn btn-default">Register</button>
            </div>
        </form>
    </div>
{% endblock %}

src/templates/users/stocks.jinja2
{% extends "base.jinja2" %}
{% block title %} {{ user }}'s stocks {% endblock %}
{% block css_includes %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/stock_scroll.css') }}">
{% endblock %}
{% block content %}
    {% block flash_messages %}
        {% include '_inline_message.jinja2' %}
    {% endblock %}
    <div class="page-header">
        <h1>Stocks <small>tracked by {{ user }}</small>
        </h1>
    </div>
    <div>
        <a class="btn btn-success" href="#" data-toggle="modal" data-target="#newStockModal">
            <span class="glyphicon glyphicon-plus"></span> Track another stock
        </a>
        <p></p>
    </div>
    <div class="list-group">
        {% for stock in stocks %}
            {% set list_history = stock.price_history.items()|list %}
            {% set success = list_history[0][1]|float < stock.moving_avg %}
            <a href="#" class="list-group-item {{ 'list-group-item-success' if success }}"
               data-toggle="modal" data-target="#{{ stock.symbol }}Modal" data-symbol={{ stock.symbol }}>
                <h4 class="list-group-item-heading">{{ stock.symbol }} </h4>
            </a>
            {% include 'users/_stock_modal.jinja2' %}
        {% endfor %}
    </div>
    <a class="btn btn-success" href="#" data-toggle="modal" data-target="#newStockModal">
        <span class="glyphicon glyphicon-plus"></span> Track another stock
    </a>
    {% include 'stocks/_new_stock_modal.jinja2' %}
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
{% endblock %}